name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: 

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Check website status
        run: |
          curl -s https://talk-to-your-csv-n9abwf4nxyhvvyr2tye5pz.streamlit.app/ > /dev/null
